[package]
name = "spotix-cli"
version = "0.1.0"
authors = ["skyline69"]
edition = "2024"

[features]
default = ["cpal"]
cpal = ["spotix-core/cpal"]
cubeb = ["spotix-core/cubeb"]

[dependencies]
spotix-core = { path = "../spotix-core" }

env_logger = "0.11.8"
log = "0.4.29"
